[package]
name = "typer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
lazy_static = "*"
clap = {version = "3.1.6", features = ["derive"] }
